using System.Globalization;

namespace SerialMitmProxy.Application.Common;

public enum UiLanguage
{
    English = 0,
    Chinese = 1,
}

public sealed record LanguageOption(UiLanguage Language, string Label);

public sealed class UiLocalizer : ViewModelBase
{
    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["WindowTitle"] = "Serial MITM Proxy V3",
        ["AppTitle"] = "Serial MITM Proxy V3",
        ["AppSubtitle"] = "Industrial Serial Monitor | Interception | Rule Pipeline | Replay",
        ["Language"] = "Language",
        ["StartSession"] = "START SESSION",
        ["StopSession"] = "STOP SESSION",
        ["AddInterceptRuleAtoB"] = "Add Intercept Rule A->B",
        ["AddInterceptRuleBtoA"] = "Add Intercept Rule B->A",
        ["Status"] = "Status",
        ["Visible"] = "Visible",
        ["BytesPerSec"] = "B/s",
        ["FramesPerSec"] = "Frames/s",
        ["SessionOverview"] = "Session Overview",
        ["Direction"] = "Direction",
        ["DirectionEndpoints"] = "EndpointA <-> EndpointB",
        ["CaptureFolder"] = "Capture Folder",
        ["ReplayControl"] = "Replay Control",
        ["SpeedFactor"] = "Speed Factor",
        ["Load"] = "Load",
        ["Replay"] = "Replay",
        ["Step"] = "Step",
        ["Browse"] = "Browse",
        ["SelectReplayFolder"] = "Select Replay Folder",
        ["SaveCurrentCaptureForReplay"] = "Save Current Capture As Replay",
        ["NoCapturedFramesToSave"] = "There are no captured frames to save.",
        ["ReplayFolderRequired"] = "Please choose a replay folder first.",
        ["ReplayCaptureSaved"] = "Replay Capture Saved",
        ["ReplayCaptureSavedMessage"] = "Saved {0} frames to replay package folder:\n{1}",
        ["ReplayCaptureSaveFailed"] = "Save Replay Capture Failed",
        ["ReplayCaptureSaveFailedMessage"] = "Failed to save replay capture: {0}",
        ["QuickNotes"] = "Quick Notes",
        ["QuickNote1"] = "Confirm endpoint A/B ports exist and are not occupied.",
        ["QuickNote2"] = "After Start, traffic enters decoder and rule pipeline.",
        ["QuickNote3"] = "Traffic remains transparent until you explicitly start interception.",
        ["QuickNote4"] = "Capture files are written into captures folder.",
        ["TabLiveMonitor"] = "Live Monitor",
        ["TabInterceptQueue"] = "Intercept Queue",
        ["TabRuleEditor"] = "Rule Editor",
        ["TabConfigEditor"] = "Config Editor",
        ["TabConfigHelp"] = "Config Help",
        ["ConfigEditorTitle"] = "Config Editor (serialmitmproxy.json)",
        ["ConfigEditorHint"] = "Edit and save parameters here. After saving, the app reloads config and restarts session for immediate packet interception.",
        ["SaveConfigAndReload"] = "Save Config + Reload + Start",
        ["CfgFieldUseInMemory"] = "Use In-Memory Endpoint",
        ["CfgFieldCaptureEnabled"] = "Enable Capture",
        ["CfgSectionEndpointA"] = "Endpoint A",
        ["CfgSectionEndpointB"] = "Endpoint B",
        ["CfgSectionEndpointAHintShort"] = "Fill in the com0com port.",
        ["CfgSectionEndpointBHintShort"] = "Fill in the physical serial port.",
        ["CfgSectionDecoder"] = "Decoder",
        ["CfgSectionRuntime"] = "Capture / Monitor / Plugin",
        ["CfgFieldPortName"] = "Port Name",
        ["CfgFieldBaudRate"] = "Baud Rate",
        ["CfgFieldDataBits"] = "Data Bits",
        ["CfgFieldParity"] = "Parity",
        ["CfgFieldStopBits"] = "Stop Bits",
        ["CfgFieldHandshake"] = "Handshake",
        ["CfgFieldDecoderMode"] = "Decoder Mode",
        ["CfgFieldTimeSliceMs"] = "Time Slice (ms)",
        ["CfgFieldDelimiterHex"] = "Delimiter HEX",
        ["CfgFieldFixedLength"] = "Fixed Length",
        ["CfgFieldCaptureFolder"] = "Capture Folder",
        ["CfgFieldMonitorMaxFrames"] = "Monitor Max Frames",
        ["CfgFieldMonitorUiThrottleMs"] = "UI Throttle (ms)",
        ["CfgFieldPluginsFolder"] = "Plugins Folder",
        ["Filter"] = "Filter",
        ["PayloadFormat"] = "Format",
        ["MonitorViewAll"] = "All Traffic",
        ["MonitorViewInbound"] = "Original Inbound",
        ["MonitorViewForwarded"] = "Forwarded Output",
        ["FilterAtoB"] = "A -> B",
        ["FilterBtoA"] = "B -> A",
        ["Hex"] = "HEX",
        ["Ascii"] = "ASCII",
        ["Clear"] = "Clear",
        ["ContextCopyHex"] = "Copy HEX",
        ["ContextCopyAscii"] = "Copy ASCII",
        ["ContextExportSelected"] = "Export Selected Frames...",
        ["ContextDeleteRule"] = "Delete Rule",
        ["ColTimestamp"] = "Timestamp",
        ["ColDirection"] = "Direction",
        ["ColSource"] = "Source",
        ["ColStatus"] = "Status",
        ["ColLength"] = "Length",
        ["ColHexPayload"] = "HEX Payload",
        ["ColAscii"] = "ASCII",
        ["SourceInbound"] = "Inbound",
        ["SourceForwarded"] = "Forwarded",
        ["ForwardedModifiedHint"] = "Modified forwarded frames are highlighted in amber.",
        ["FrameOriginal"] = "Original",
        ["FrameModified"] = "Modified",
        ["DirAtoB"] = "A -> B",
        ["DirBtoA"] = "B -> A",
        ["ColEditableHex"] = "Editable HEX",
        ["Forward"] = "Forward",
        ["Drop"] = "Drop",
        ["EditAndForward"] = "Edit + Forward",
        ["RepeatX2"] = "Repeat x2",
        ["RepeatX2Hint"] = "Send the current intercepted frame twice in total with the original payload.",
        ["StartIntercept"] = "Start Intercept",
        ["StopIntercept"] = "Stop Intercept",
        ["InterceptModeEnabled"] = "Interception is active",
        ["InterceptModeDisabled"] = "Transparent proxy mode",
        ["InterceptModeEnabledHint"] = "Frames matching intercept rules are blocked here until you forward, edit, or drop them.",
        ["InterceptModeDisabledHint"] = "Traffic is forwarded immediately. Live Monitor still shows all traffic, but nothing is blocked in this queue.",
        ["PendingRequests"] = "Pending",
        ["ChecksumToolTitle"] = "Checksum / CRC Helper",
        ["ChecksumAlgorithm"] = "Algorithm",
        ["ChecksumValue"] = "Result",
        ["OverwriteTailChecksum"] = "Overwrite At Offset",
        ["AppendChecksum"] = "Append",
        ["ChecksumStartOffset"] = "Start Offset",
        ["ChecksumEndOffset"] = "End Offset",
        ["ChecksumWriteOffset"] = "Write Offset",
        ["ChecksumByteOrder"] = "Byte Order",
        ["ChecksumByteOrderLittle"] = "Little-endian",
        ["ChecksumByteOrderBig"] = "Big-endian",
        ["ChecksumAutoOffsetHint"] = "Use -1 for auto.",
        ["ChecksumAlgoSum8"] = "Checksum-8 (SUM)",
        ["ChecksumAlgoXor8"] = "Checksum-8 (XOR)",
        ["ChecksumAlgoCrc8"] = "CRC-8",
        ["ChecksumAlgoCrc16Modbus"] = "CRC-16/MODBUS",
        ["ChecksumAlgoCrc16Ibm"] = "CRC-16/IBM",
        ["ChecksumAlgoCrc16Ccitt"] = "CRC-16/CCITT-FALSE",
        ["ChecksumAlgoLrc"] = "LRC",
        ["ChecksumAlgoBcc"] = "BCC",
        ["ChecksumAlgoCrc32"] = "CRC-32",
        ["ChecksumScopeBytes"] = "Calculated over bytes {0}..{1}",
        ["ChecksumScopeEmpty"] = "Calculated over an empty payload range.",
        ["ChecksumTailHint"] = "Tail overwrite reserves the last {0} byte(s) as checksum field.",
        ["ChecksumAutoRangeHint"] = "Auto End Offset excludes the last {0} byte(s) when enough room is available.",
        ["ChecksumWriteHint"] = "Overwrite target: bytes {0}..{1}.",
        ["ChecksumAppendOnlyHint"] = "Current payload is shorter than the checksum width, so only Append is available.",
        ["ChecksumByteOrderHint"] = "Byte order: {0}.",
        ["ChecksumSelectFrameFirst"] = "Select an intercepted frame first.",
        ["ChecksumInvalidHex"] = "Edited payload is invalid: {0}",
        ["ChecksumPayloadTooShort"] = "Payload is shorter than the selected checksum width.",
        ["ChecksumInvalidRange"] = "Invalid checksum range. Start={0}, End={1}. Use -1 for auto End Offset.",
        ["ChecksumInvalidWriteOffset"] = "Invalid write offset: {0}. Use -1 for auto or provide a valid target range.",
        ["EditPayloadInvalid"] = "Invalid HEX Payload",
        ["EditPayloadInvalidMessage"] = "Edited payload is invalid: {0}",
        ["ColRuleName"] = "Rule Name",
        ["ColEnabled"] = "Enabled",
        ["ColScope"] = "Scope",
        ["ColMatchers"] = "Matchers",
        ["ColActions"] = "Actions",
        ["RuleScopeProxy"] = "Proxy",
        ["RuleScopeMonitor"] = "Monitor",
        ["AddHexMonitorRule"] = "Add HEX Filter Rule...",
        ["AddAsciiMonitorRule"] = "Add ASCII Match Rule...",
        ["AddHexMonitorRuleDescription"] = "Add a HEX pattern allow-list rule. Only traffic matching enabled monitor rules remains visible in Live Monitor.",
        ["AddAsciiMonitorRuleDescription"] = "Add an ASCII regex allow-list rule. Only traffic matching enabled monitor rules remains visible in Live Monitor.",
        ["RuleName"] = "Rule Name",
        ["HexPattern"] = "HEX Pattern",
        ["AsciiRegex"] = "ASCII Regex",
        ["HexMonitorRuleHint"] = "Example: AA ?? CC. Use spaces between bytes; ?? means wildcard.",
        ["AsciiMonitorRuleHint"] = "Example: PING|PONG or ^OK. The pattern is evaluated against ASCII payload.",
        ["AddRule"] = "Add Rule",
        ["Cancel"] = "Cancel",
        ["DirectionAll"] = "All Directions",
        ["MonitorRulePatternRequired"] = "Pattern cannot be empty.",
        ["MonitorRuleInvalid"] = "Invalid Monitor Rule",
        ["MonitorRuleInvalidMessage"] = "Monitor rule is invalid: {0}",
        ["RuleKindHexFilter"] = "HexFilter",
        ["RuleKindAsciiMatch"] = "AsciiMatch",
        ["StatusObservedFrames"] = "Observed Frames",

        ["StatusIdle"] = "Idle",
        ["StatusRunning"] = "Running",
        ["StatusStopped"] = "Stopped",
        ["StatusStartFailed"] = "Start failed: {0}",
        ["StatusRunningRulesUpdated"] = "Running (Rules updated: {0})",
        ["StatusStopFailed"] = "Stop failed: {0}",
        ["StatusSessionError"] = "Session error: {0}",

        ["StartSessionFailed"] = "Start Session Failed",
        ["StopSessionFailed"] = "Stop Session Failed",
        ["UnexpectedError"] = "Unexpected error: {0}",
        ["StopSessionFailedMessage"] = "Stop failed: {0}",
        ["RuleAdded"] = "Rule Added",
        ["RuleAddedRunning"] = "Intercept rule for {0} is added to the current session. Traffic remains transparent until you start interception in Intercept Queue.",
        ["RuleAddedNotRunning"] = "Intercept rule for {0} is added. Start Session to activate it. Traffic remains transparent until you start interception in Intercept Queue.",
        ["NoFrameSelected"] = "No frame selected.",
        ["CopyHex"] = "Copy HEX",
        ["CopyAscii"] = "Copy ASCII",
        ["ExportFrames"] = "Export Frames",
        ["ExportDialogFilter"] = "CSV files (*.csv)|*.csv|Text files (*.txt)|*.txt",
        ["ReplayLoaded"] = "Replay Loaded",
        ["ReplayLoadedMessage"] = "Replay data loaded. Frames: {0}",
        ["ReplayLoadFailed"] = "Replay Load Failed",
        ["ReplayLoadFailedMessage"] = "Load failed: {0}",
        ["ReplayFailed"] = "Replay Failed",
        ["ReplayFailedMessage"] = "Replay failed: {0}",
        ["ReplayStep"] = "Replay Step",
        ["ReplayStepNoMore"] = "No more replay frames or replay data is not loaded.",
        ["ReplayStepFailed"] = "Replay step failed: {0}",
        ["ConfigSaved"] = "Config Saved",
        ["ConfigSavedReloaded"] = "Configuration saved and reloaded. Session restarted with new parameters.",
        ["ConfigSavedStartFailed"] = "Configuration saved, but restart failed.\n{0}",
        ["ConfigSaveFailed"] = "Config Save Failed",
        ["ConfigSaveFailedMessage"] = "Save or reload failed: {0}",
        ["ConfigHelpTitle"] = "Configuration Help (serialmitmproxy.json)",
        ["ConfigHelpIntro"] = "This panel explains each config field and its expected values. The same key paths apply to serialmitmproxy.template.json.",
        ["ConfigSessionSection"] = "session",
        ["CfgSessionUseInMemory"] = "true uses in-memory endpoints for local testing; false uses real serial ports.",
        ["CfgSessionEndpointA"] = "Endpoint A serial settings object: portName, baudRate, dataBits, parity, stopBits, handshake.",
        ["CfgSessionEndpointB"] = "Endpoint B serial settings object. Keep protocol parameters aligned with Endpoint A unless your device requires mismatch.",
        ["CfgSessionDecoderMode"] = "Frame split mode: TimeSlice / Delimiter / FixedLength.",
        ["CfgSessionDecoderTimeSlice"] = "Used only when mode=TimeSlice. Unit: milliseconds.",
        ["CfgSessionDecoderDelimiter"] = "Used only when mode=Delimiter. HEX bytes separated by spaces, e.g. 0D 0A.",
        ["CfgSessionDecoderFixedLength"] = "Used only when mode=FixedLength. Unit: bytes.",
        ["ConfigCaptureSection"] = "capture",
        ["CfgCaptureEnabled"] = "Enable or disable capture file output.",
        ["CfgCaptureFolder"] = "Capture root directory. Each session generates a timestamped subfolder.",
        ["ConfigMonitorSection"] = "monitor",
        ["CfgMonitorMaxFrames"] = "Maximum in-memory frames retained by the UI.",
        ["CfgMonitorUiThrottle"] = "UI refresh throttle in milliseconds to reduce render overhead.",
        ["ConfigPluginSection"] = "plugins",
        ["CfgPluginsFolder"] = "Plugin DLL scanning folder. All IFramePlugin implementations under this folder are loaded on session start.",
    };

    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["WindowTitle"] = "串口中间人代理 V3",
        ["AppTitle"] = "串口中间人代理 V3",
        ["AppSubtitle"] = "工业串口监视 | 拦截决策 | 规则流水线 | 捕获回放",
        ["Language"] = "语言",
        ["StartSession"] = "启动会话",
        ["StopSession"] = "停止会话",
        ["AddInterceptRuleAtoB"] = "添加 A->B 拦截规则",
        ["AddInterceptRuleBtoA"] = "添加 B->A 拦截规则",
        ["Status"] = "状态",
        ["Visible"] = "可见",
        ["BytesPerSec"] = "字节/秒",
        ["FramesPerSec"] = "帧/秒",
        ["SessionOverview"] = "会话概览",
        ["Direction"] = "方向",
        ["DirectionEndpoints"] = "端点A <-> 端点B",
        ["CaptureFolder"] = "捕获目录",
        ["ReplayControl"] = "回放控制",
        ["SpeedFactor"] = "倍速系数",
        ["Load"] = "加载",
        ["Replay"] = "回放",
        ["Step"] = "单步",
        ["Browse"] = "选择目录",
        ["SelectReplayFolder"] = "选择回放目录",
        ["SaveCurrentCaptureForReplay"] = "保存当前捕获为回放包",
        ["NoCapturedFramesToSave"] = "当前没有可保存的捕获帧。",
        ["ReplayFolderRequired"] = "请先选择回放目录。",
        ["ReplayCaptureSaved"] = "回放包已保存",
        ["ReplayCaptureSavedMessage"] = "已保存 {0} 条帧到回放包目录：\n{1}",
        ["ReplayCaptureSaveFailed"] = "保存回放包失败",
        ["ReplayCaptureSaveFailedMessage"] = "保存回放包失败：{0}",
        ["QuickNotes"] = "快速说明",
        ["QuickNote1"] = "请先确认 A/B 端口存在且未被占用。",
        ["QuickNote2"] = "启动后，流量会进入解码与规则流水线。",
        ["QuickNote3"] = "只有你主动开启拦截后，流量才会进入拦截队列。",
        ["QuickNote4"] = "捕获文件会写入 captures 目录。",
        ["TabLiveMonitor"] = "实时监控",
        ["TabInterceptQueue"] = "拦截队列",
        ["TabRuleEditor"] = "规则编辑",
        ["TabConfigEditor"] = "配置编辑",
        ["TabConfigHelp"] = "配置帮助",
        ["ConfigEditorTitle"] = "配置编辑（serialmitmproxy.json）",
        ["ConfigEditorHint"] = "可在此直接修改并保存配置。保存后程序会重新加载配置并自动重启会话开始截包。",
        ["SaveConfigAndReload"] = "保存配置并重载启动",
        ["CfgFieldUseInMemory"] = "使用内存端点",
        ["CfgFieldCaptureEnabled"] = "启用捕获",
        ["CfgSectionEndpointA"] = "端点 A",
        ["CfgSectionEndpointB"] = "端点 B",
        ["CfgSectionEndpointAHintShort"] = "填写 com0com 串口",
        ["CfgSectionEndpointBHintShort"] = "填写物理串口",
        ["CfgSectionDecoder"] = "解码配置",
        ["CfgSectionRuntime"] = "捕获 / 监控 / 插件",
        ["CfgFieldPortName"] = "串口号",
        ["CfgFieldBaudRate"] = "波特率",
        ["CfgFieldDataBits"] = "数据位",
        ["CfgFieldParity"] = "校验位",
        ["CfgFieldStopBits"] = "停止位",
        ["CfgFieldHandshake"] = "握手",
        ["CfgFieldDecoderMode"] = "分帧模式",
        ["CfgFieldTimeSliceMs"] = "时间片（毫秒）",
        ["CfgFieldDelimiterHex"] = "分隔符 HEX",
        ["CfgFieldFixedLength"] = "固定长度",
        ["CfgFieldCaptureFolder"] = "捕获目录",
        ["CfgFieldMonitorMaxFrames"] = "监控最大帧数",
        ["CfgFieldMonitorUiThrottleMs"] = "UI 节流（毫秒）",
        ["CfgFieldPluginsFolder"] = "插件目录",
        ["Filter"] = "过滤",
        ["PayloadFormat"] = "格式",
        ["MonitorViewAll"] = "全部流量",
        ["MonitorViewInbound"] = "原始入站",
        ["MonitorViewForwarded"] = "实际转发后",
        ["FilterAtoB"] = "A -> B",
        ["FilterBtoA"] = "B -> A",
        ["Hex"] = "HEX",
        ["Ascii"] = "ASCII",
        ["Clear"] = "清空",
        ["ContextCopyHex"] = "复制 HEX",
        ["ContextCopyAscii"] = "复制 ASCII",
        ["ContextExportSelected"] = "导出所选帧...",
        ["ContextDeleteRule"] = "删除规则",
        ["ColTimestamp"] = "时间戳",
        ["ColDirection"] = "方向",
        ["ColSource"] = "来源",
        ["ColStatus"] = "状态",
        ["ColLength"] = "长度",
        ["ColHexPayload"] = "HEX 载荷",
        ["ColAscii"] = "ASCII",
        ["SourceInbound"] = "入站",
        ["SourceForwarded"] = "转发后",
        ["ForwardedModifiedHint"] = "已修改后再转发的报文会用琥珀色高亮显示。",
        ["FrameOriginal"] = "原样",
        ["FrameModified"] = "已修改",
        ["DirAtoB"] = "A -> B",
        ["DirBtoA"] = "B -> A",
        ["ColEditableHex"] = "可编辑 HEX",
        ["Forward"] = "转发",
        ["Drop"] = "丢弃",
        ["EditAndForward"] = "编辑后转发",
        ["RepeatX2"] = "重复 x2",
        ["RepeatX2Hint"] = "将当前被拦截的这条报文按原始内容总共发送两次。",
        ["StartIntercept"] = "开启拦截",
        ["StopIntercept"] = "停止拦截",
        ["InterceptModeEnabled"] = "当前正在拦截",
        ["InterceptModeDisabled"] = "当前为透明代理模式",
        ["InterceptModeEnabledHint"] = "命中拦截规则的帧会在这里被阻断，等待你执行转发、修改转发或丢弃等操作。",
        ["InterceptModeDisabledHint"] = "流量会立即透传。Live Monitor 仍会展示全部流量，但这里不会阻断任何帧。",
        ["PendingRequests"] = "待处理",
        ["ChecksumToolTitle"] = "校验 / CRC 助手",
        ["ChecksumAlgorithm"] = "算法",
        ["ChecksumValue"] = "结果",
        ["OverwriteTailChecksum"] = "按偏移覆盖",
        ["AppendChecksum"] = "追加校验",
        ["ChecksumStartOffset"] = "起始偏移",
        ["ChecksumEndOffset"] = "结束偏移",
        ["ChecksumWriteOffset"] = "写回偏移",
        ["ChecksumByteOrder"] = "字节序",
        ["ChecksumByteOrderLittle"] = "小端",
        ["ChecksumByteOrderBig"] = "大端",
        ["ChecksumAutoOffsetHint"] = "填 -1 表示自动。",
        ["ChecksumAlgoSum8"] = "Checksum-8（求和）",
        ["ChecksumAlgoXor8"] = "Checksum-8（异或）",
        ["ChecksumAlgoCrc8"] = "CRC-8",
        ["ChecksumAlgoCrc16Modbus"] = "CRC-16/MODBUS",
        ["ChecksumAlgoCrc16Ibm"] = "CRC-16/IBM",
        ["ChecksumAlgoCrc16Ccitt"] = "CRC-16/CCITT-FALSE",
        ["ChecksumAlgoLrc"] = "LRC",
        ["ChecksumAlgoBcc"] = "BCC",
        ["ChecksumAlgoCrc32"] = "CRC-32",
        ["ChecksumScopeBytes"] = "计算范围：字节 {0}..{1}",
        ["ChecksumScopeEmpty"] = "当前按空载荷范围计算。",
        ["ChecksumTailHint"] = "覆盖尾部时，默认将最后 {0} 个字节视为校验位。",
        ["ChecksumAutoRangeHint"] = "结束偏移为自动时，如果报文长度足够，会自动排除最后 {0} 个字节。",
        ["ChecksumWriteHint"] = "覆盖目标：字节 {0}..{1}。",
        ["ChecksumAppendOnlyHint"] = "当前报文长度小于校验位宽度，因此只能追加校验。",
        ["ChecksumByteOrderHint"] = "当前字节序：{0}。",
        ["ChecksumSelectFrameFirst"] = "请先选择一条被拦截的报文。",
        ["ChecksumInvalidHex"] = "编辑后的报文格式无效：{0}",
        ["ChecksumPayloadTooShort"] = "当前报文长度小于所选校验位宽度。",
        ["ChecksumInvalidRange"] = "校验范围无效。Start={0}, End={1}。结束偏移可填 -1 表示自动。",
        ["ChecksumInvalidWriteOffset"] = "写回偏移无效：{0}。可填 -1 表示自动，或填写有效覆盖范围。",
        ["EditPayloadInvalid"] = "HEX 报文格式无效",
        ["EditPayloadInvalidMessage"] = "编辑后的报文格式无效：{0}",
        ["ColRuleName"] = "规则名称",
        ["ColEnabled"] = "启用",
        ["ColScope"] = "范围",
        ["ColMatchers"] = "匹配器",
        ["ColActions"] = "动作",
        ["RuleScopeProxy"] = "代理",
        ["RuleScopeMonitor"] = "监控",
        ["AddHexMonitorRule"] = "添加 HEX 过滤规则...",
        ["AddAsciiMonitorRule"] = "添加 ASCII 匹配规则...",
        ["AddHexMonitorRuleDescription"] = "添加 HEX 模式允许规则。启用监控规则后，Live Monitor 只显示命中这些规则的流量。",
        ["AddAsciiMonitorRuleDescription"] = "添加 ASCII 正则允许规则。启用监控规则后，Live Monitor 只显示命中这些规则的流量。",
        ["RuleName"] = "规则名称",
        ["HexPattern"] = "HEX 模式",
        ["AsciiRegex"] = "ASCII 正则",
        ["HexMonitorRuleHint"] = "示例：AA ?? CC。字节之间用空格分隔，?? 表示通配。",
        ["AsciiMonitorRuleHint"] = "示例：PING|PONG 或 ^OK。该模式会对 ASCII 载荷做正则匹配。",
        ["AddRule"] = "添加规则",
        ["Cancel"] = "取消",
        ["DirectionAll"] = "全部方向",
        ["MonitorRulePatternRequired"] = "匹配内容不能为空。",
        ["MonitorRuleInvalid"] = "监控规则无效",
        ["MonitorRuleInvalidMessage"] = "监控规则无效：{0}",
        ["RuleKindHexFilter"] = "HEX过滤",
        ["RuleKindAsciiMatch"] = "ASCII匹配",
        ["StatusObservedFrames"] = "已观测帧",

        ["StatusIdle"] = "空闲",
        ["StatusRunning"] = "运行中",
        ["StatusStopped"] = "已停止",
        ["StatusStartFailed"] = "启动失败：{0}",
        ["StatusRunningRulesUpdated"] = "运行中（规则已更新：{0}）",
        ["StatusStopFailed"] = "停止失败：{0}",
        ["StatusSessionError"] = "会话错误：{0}",

        ["StartSessionFailed"] = "启动会话失败",
        ["StopSessionFailed"] = "停止会话失败",
        ["UnexpectedError"] = "发生未预期错误：{0}",
        ["StopSessionFailedMessage"] = "停止失败：{0}",
        ["RuleAdded"] = "规则已添加",
        ["RuleAddedRunning"] = "已将 {0} 拦截规则加入当前会话。只有在拦截队列中主动开启拦截后，流量才会被阻断。",
        ["RuleAddedNotRunning"] = "已添加 {0} 拦截规则。启动会话后生效；只有在拦截队列中主动开启拦截后，流量才会被阻断。",
        ["NoFrameSelected"] = "未选择任何帧。",
        ["CopyHex"] = "复制 HEX",
        ["CopyAscii"] = "复制 ASCII",
        ["ExportFrames"] = "导出帧",
        ["ExportDialogFilter"] = "CSV 文件 (*.csv)|*.csv|文本文件 (*.txt)|*.txt",
        ["ReplayLoaded"] = "回放数据已加载",
        ["ReplayLoadedMessage"] = "回放数据加载完成，帧数：{0}",
        ["ReplayLoadFailed"] = "加载回放失败",
        ["ReplayLoadFailedMessage"] = "加载失败：{0}",
        ["ReplayFailed"] = "回放失败",
        ["ReplayFailedMessage"] = "回放失败：{0}",
        ["ReplayStep"] = "单步回放",
        ["ReplayStepNoMore"] = "没有更多回放帧，或尚未加载回放数据。",
        ["ReplayStepFailed"] = "单步回放失败：{0}",
        ["ConfigSaved"] = "配置已保存",
        ["ConfigSavedReloaded"] = "配置已保存并重载，会话已按新参数自动重启。",
        ["ConfigSavedStartFailed"] = "配置已保存，但重启失败。\n{0}",
        ["ConfigSaveFailed"] = "配置保存失败",
        ["ConfigSaveFailedMessage"] = "保存或重载失败：{0}",
        ["ConfigHelpTitle"] = "配置文件帮助（serialmitmproxy.json）",
        ["ConfigHelpIntro"] = "此面板用于说明配置字段含义与可填写值。同样的键路径也适用于 serialmitmproxy.template.json。",
        ["ConfigSessionSection"] = "session",
        ["CfgSessionUseInMemory"] = "true 使用内存端点（本地联调/测试）；false 使用真实串口端点。",
        ["CfgSessionEndpointA"] = "端点 A 串口配置对象：portName、baudRate、dataBits、parity、stopBits、handshake。",
        ["CfgSessionEndpointB"] = "端点 B 串口配置对象。除非设备协议要求不同，建议与端点 A 保持一致。",
        ["CfgSessionDecoderMode"] = "分帧模式：TimeSlice / Delimiter / FixedLength。",
        ["CfgSessionDecoderTimeSlice"] = "仅在 mode=TimeSlice 时生效，单位毫秒。",
        ["CfgSessionDecoderDelimiter"] = "仅在 mode=Delimiter 时生效，HEX 字节以空格分隔，例如 0D 0A。",
        ["CfgSessionDecoderFixedLength"] = "仅在 mode=FixedLength 时生效，单位字节。",
        ["ConfigCaptureSection"] = "capture",
        ["CfgCaptureEnabled"] = "是否启用捕获文件输出。",
        ["CfgCaptureFolder"] = "捕获根目录，每次会话会生成时间戳子目录。",
        ["ConfigMonitorSection"] = "monitor",
        ["CfgMonitorMaxFrames"] = "UI 在内存中保留的最大帧数。",
        ["CfgMonitorUiThrottle"] = "UI 刷新节流周期（毫秒），用于降低渲染开销。",
        ["ConfigPluginSection"] = "plugins",
        ["CfgPluginsFolder"] = "插件 DLL 扫描目录。会话启动时会加载目录下所有 IFramePlugin 实现。",
    };

    private readonly LanguageOption[] _languageOptions =
    {
        new LanguageOption(UiLanguage.English, "English"),
        new LanguageOption(UiLanguage.Chinese, "中文"),
    };

    private UiLanguage _currentLanguage;

    public UiLocalizer()
    {
        _currentLanguage = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("zh", StringComparison.OrdinalIgnoreCase)
            ? UiLanguage.Chinese
            : UiLanguage.English;
    }

    public IReadOnlyList<LanguageOption> LanguageOptions => _languageOptions;

    public UiLanguage CurrentLanguage
    {
        get => _currentLanguage;
        set
        {
            if (!SetProperty(ref _currentLanguage, value))
            {
                return;
            }

            RaisePropertyChanged("Item[]");
        }
    }

    public string this[string key] => Translate(key);

    public string Translate(string key)
    {
        var source = CurrentLanguage == UiLanguage.Chinese ? Chinese : English;
        return source.TryGetValue(key, out var text) ? text : key;
    }
}
